// <auto-generated />
namespace DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_load_and_sunriseSunsetTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_load_and_sunriseSunsetTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201111344236_delete_load_and_sunriseSunsetTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
